### ISSUE TITLE
天天改有意思吗，每次都能搜到你的

### ISSUE THREAD

**Issue by gaozhen123456** [revenol/LyDROO#1]

**Comment by revenol** [comment]
If you are watching a repository, you will receive notifications for all discussions — project issues, pull requests, comments on commits and any other comments. If you’re not watching a repo you’ll just receive notification for the discussions you participate in.

On the other hand, if you star a repository, you basically want to show your appreciation as well as keep track of repositories that you find interesting without it spamming your timeline.
