### ISSUE TITLE
关于按泊松分布到达数据的生成方式

### ISSUE THREAD

**Issue by Wesley273** [revenol/LyDROO#6]
```
# real-time arrival generation         
dataA[i, :] = np.random.exponential(arrival_lambda)
```
这样生成的不应该是一系列任务到达间隔么？为什么可以用来代指每个时隙内到达的数据量？

**Comment by revenol** [comment]
lambda是arrival rate，单位时隙到达的任务量。算法只需要满足 i.i.d. 分布，仿真用的指数分布。
本文假设每个时隙都有可变的任务量到达，并不是泊松分布的到达间隔。泊松分布到达与指数函数间隔之间的关系，感觉你已经掌握了，所以才有此问。
