### ISSUE TITLE
请问关于多进制卸载您有什么见解么

### ISSUE THREAD

**Issue by Wesley273** [revenol/LyDROO#7]
目前这方面的工作似乎都是二进制卸载？即x={0,1}，但如果是多个WD，多个EC，每个WD可以决策卸载到任意一个EC，甚至可以通过多种路径（中继转发、直接传输），这时候应该如何考虑呢？有无相关工作

**Comment by revenol** [comment]
本文主要探讨如何将长时隙约束问题转化位单时隙约束优化问题，并用深度强化学习求解该单时隙问题。你可以找找单时隙下是否有算法能解决你的问题，然后替代该深度强化学习模块。
